language: bash
sudo: required
os: linux-ppc64le

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq build-essential libicu-dev libssl-dev gperf bison ruby flex

script: ./build -c -r
